# Blowfish theme parameters

colorScheme = "fire"
defaultAppearance = "dark"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = false

disableImageOptimization = false

defaultBackgroundImage = "image.jpg"

highlightCurrentMenuArea = true

[header]
    layout = "fixed"

[footer]
    showMenu = true
    showCopyright = true
    showThemeAttribution = true
    showAppearanceSwitcher = true
    showScrollToTop = true

[homepage]
    layout = "background"
    # homepageImage = "background.jpg"
    showRecent = true
    showRecentItems = 6
    showMoreLink = true
    showMoreLinkDest = "/posts"
    cardView = true
    cardViewScreenWidth = false
    layoutBackgroundBlur = true

[article]
    showDate = true
    showViews = false
    showLikes = false
    showDateUpdated = false
    showAuthor = false
    showHero = true
    heroStyle = "background"
    layoutBackgroundBlur = true
    layoutBackgroundHeaderSpace = true
    showBreadcrumbs = false
    showDraftLabel = true
    showEdit = false
    editAppendPath = true
    seriesOpened = false
    showHeadingAnchors = true
    showPagination = true
    showReadingTime = true
    showTableOfContents = true
    showRelatedContent = true
    relatedContentLimit = 3
    showTaxonomies = false
    showAuthorsBadges = false
    showWordCount = true

[list]
    showHero = true
    heroStyle = "background"
    layoutBackgroundBlur = true
    layoutBackgroundHeaderSpace = true
    showBreadcrumbs = false
    showSummary = true
    showViews = false
    showLikes = false
    showTableOfContents = false
    showCards = true
    groupByYear = false
    cardView = true
    cardViewScreenWidth = false
    constrainItemsWidth = false

[sitemap]
    excludedKinds = ["taxonomy", "term"]

[taxonomy]
    showTermCount = true
    showHero = false
    showBreadcrumbs = false
    showViews = false
    showLikes = false
    showTableOfContents = false
    cardView = false

[term]
    showHero = false
    # heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
    showBreadcrumbs = false
    showViews = false
    showLikes = false
    showTableOfContents = true
    groupByYear = false
    cardView = false
    cardViewScreenWidth = false
